server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tauto_core?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.email.us-sanjose-1.oci.oraclecloud.com
    port: 587
    username: ocid1.user.oc1..aaaaaaaa6cwlipxsion2gsbcr3lni2rjphptuq2fpwcihehhibc6ezyynlya@ocid1.tenancy.oc1..aaaaaaaa2b233ssbxlsyqf52ez7zoooymnms7llw67coqvfeir4umo2wyzba.tc.com
    password: E{9N)o8u4+d9$xH]mW<W
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

oci:
  objectstorage:
    namespace: axdbbhb5ebzz
    bucket: tauto-user-photos
    region: us-sanjose-1

app:
  admin-key: "hbdt"
  credential-ttl-seconds: 180
  credential-secret: "cambia-este-secreto-en-produccion"
  benefits-upload-dir: "uploads/benefits"
  mail:
    from: SindicatoHbdt@Tauto.cl